version: '3.8'

services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile-db
    container_name: DiscordBotdb
    restart: always
    volumes:
      - ./backup:/backup
  bot:
    build:
      context: ./
      dockerfile: Dockerfile-bot
    container_name: DiscordBotbot
    restart: always
    volumes:
      - ./bot:/bot
    env_file:
      - ./.env
    depends_on:
      - DiscordBotdb
